# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 725)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timeseriesgraphWidget = PlotWidget(self.centralwidget)
        self.timeseriesgraphWidget.setGeometry(QtCore.QRect(480, 40, 691, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeseriesgraphWidget.sizePolicy().hasHeightForWidth())
        self.timeseriesgraphWidget.setSizePolicy(sizePolicy)
        self.timeseriesgraphWidget.setObjectName("timeseriesgraphWidget")
        self.selectData = QtWidgets.QPushButton(self.centralwidget)
        self.selectData.setGeometry(QtCore.QRect(170, 330, 291, 51))
        self.selectData.setObjectName("selectData")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 40, 451, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMidLineWidth(1)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableView.setObjectName("tableView")
        self.startIndex = QtWidgets.QTextEdit(self.centralwidget)
        self.startIndex.setEnabled(True)
        self.startIndex.setGeometry(QtCore.QRect(30, 350, 61, 31))
        self.startIndex.setObjectName("startIndex")
        self.endIndex = QtWidgets.QTextEdit(self.centralwidget)
        self.endIndex.setEnabled(True)
        self.endIndex.setGeometry(QtCore.QRect(100, 350, 61, 31))
        self.endIndex.setObjectName("endIndex")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(30, 330, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(100, 330, 71, 16))
        self.label_2.setObjectName("label_2")
        self.clearAndPlotData_button = QtWidgets.QPushButton(self.centralwidget)
        self.clearAndPlotData_button.setGeometry(QtCore.QRect(170, 390, 291, 51))
        self.clearAndPlotData_button.setObjectName("clearAndPlotData_button")
        self.button_Update = QtWidgets.QPushButton(self.centralwidget)
        self.button_Update.setGeometry(QtCore.QRect(30, 390, 131, 51))
        self.button_Update.setObjectName("button_Update")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 320, 451, 131))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 460, 451, 201))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(40, 470, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(40, 500, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(240, 470, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(380, 470, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.savitzkyOrder = QtWidgets.QSlider(self.centralwidget)
        self.savitzkyOrder.setGeometry(QtCore.QRect(190, 500, 121, 22))
        self.savitzkyOrder.setMinimum(1)
        self.savitzkyOrder.setMaximum(11)
        self.savitzkyOrder.setSingleStep(1)
        self.savitzkyOrder.setOrientation(QtCore.Qt.Horizontal)
        self.savitzkyOrder.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.savitzkyOrder.setTickInterval(2)
        self.savitzkyOrder.setObjectName("savitzkyOrder")
        self.savitzkyLength = QtWidgets.QSlider(self.centralwidget)
        self.savitzkyLength.setGeometry(QtCore.QRect(320, 500, 141, 22))
        self.savitzkyLength.setMinimum(3)
        self.savitzkyLength.setMaximum(31)
        self.savitzkyLength.setSingleStep(2)
        self.savitzkyLength.setOrientation(QtCore.Qt.Horizontal)
        self.savitzkyLength.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.savitzkyLength.setTickInterval(4)
        self.savitzkyLength.setObjectName("savitzkyLength")
        self.savitzkyCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.savitzkyCheckbox.setGeometry(QtCore.QRect(110, 500, 21, 17))
        self.savitzkyCheckbox.setText("")
        self.savitzkyCheckbox.setObjectName("savitzkyCheckbox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(40, 540, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.highpassCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.highpassCheckbox.setGeometry(QtCore.QRect(110, 540, 21, 17))
        self.highpassCheckbox.setText("")
        self.highpassCheckbox.setObjectName("highpassCheckbox")
        self.labelSavitzkyOrder = QtWidgets.QLabel(self.centralwidget)
        self.labelSavitzkyOrder.setGeometry(QtCore.QRect(260, 490, 47, 13))
        self.labelSavitzkyOrder.setObjectName("labelSavitzkyOrder")
        self.labelSavitzkyLength = QtWidgets.QLabel(self.centralwidget)
        self.labelSavitzkyLength.setGeometry(QtCore.QRect(420, 490, 47, 13))
        self.labelSavitzkyLength.setObjectName("labelSavitzkyLength")
        self.labelHighpassCutoff = QtWidgets.QLabel(self.centralwidget)
        self.labelHighpassCutoff.setEnabled(True)
        self.labelHighpassCutoff.setGeometry(QtCore.QRect(430, 530, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelHighpassCutoff.setFont(font)
        self.labelHighpassCutoff.setObjectName("labelHighpassCutoff")
        self.highpassCutoff = QtWidgets.QSlider(self.centralwidget)
        self.highpassCutoff.setGeometry(QtCore.QRect(190, 540, 271, 22))
        self.highpassCutoff.setMaximum(10)
        self.highpassCutoff.setOrientation(QtCore.Qt.Horizontal)
        self.highpassCutoff.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.highpassCutoff.setObjectName("highpassCutoff")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(40, 580, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.detrendCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.detrendCheckbox.setGeometry(QtCore.QRect(110, 580, 21, 17))
        self.detrendCheckbox.setText("")
        self.detrendCheckbox.setObjectName("detrendCheckbox")
        self.detrendBreakpointsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.detrendBreakpointsLineEdit.setGeometry(QtCore.QRect(210, 580, 251, 20))
        self.detrendBreakpointsLineEdit.setObjectName("detrendBreakpointsLineEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(140, 580, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 600, 251, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(40, 620, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.alsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.alsLineEdit.setGeometry(QtCore.QRect(210, 620, 251, 20))
        self.alsLineEdit.setObjectName("alsLineEdit")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(210, 640, 251, 16))
        self.label_12.setObjectName("label_12")
        self.alsCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.alsCheckbox.setGeometry(QtCore.QRect(180, 620, 21, 17))
        self.alsCheckbox.setText("")
        self.alsCheckbox.setObjectName("alsCheckbox")
        self.loadDisplacementWidget = PlotWidget(self.centralwidget)
        self.loadDisplacementWidget.setGeometry(QtCore.QRect(480, 380, 431, 281))
        self.loadDisplacementWidget.setObjectName("loadDisplacementWidget")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 61, 21))
        self.label_13.setObjectName("label_13")
        self.currentFilePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentFilePathLabel.setGeometry(QtCore.QRect(90, 10, 381, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentFilePathLabel.setFont(font)
        self.currentFilePathLabel.setText("")
        self.currentFilePathLabel.setObjectName("currentFilePathLabel")
        self.heightWidthGaplengthLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.heightWidthGaplengthLineEdit.setGeometry(QtCore.QRect(920, 400, 251, 20))
        self.heightWidthGaplengthLineEdit.setObjectName("heightWidthGaplengthLineEdit")
        self.heightWidthGaplengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.heightWidthGaplengthLabel.setGeometry(QtCore.QRect(920, 380, 251, 16))
        self.heightWidthGaplengthLabel.setObjectName("heightWidthGaplengthLabel")
        self.convertToStressStrainButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertToStressStrainButton.setGeometry(QtCore.QRect(920, 430, 121, 61))
        self.convertToStressStrainButton.setObjectName("convertToStressStrainButton")
        self.convertToLoadDisplacement = QtWidgets.QPushButton(self.centralwidget)
        self.convertToLoadDisplacement.setGeometry(QtCore.QRect(1050, 430, 121, 61))
        self.convertToLoadDisplacement.setObjectName("convertToLoadDisplacement")
        self.youngsModulusTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.youngsModulusTextEdit.setEnabled(True)
        self.youngsModulusTextEdit.setGeometry(QtCore.QRect(920, 500, 81, 21))
        self.youngsModulusTextEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.youngsModulusTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.youngsModulusTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.youngsModulusTextEdit.setObjectName("youngsModulusTextEdit")
        self.heightWidthGaplengthLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.heightWidthGaplengthLabel_2.setGeometry(QtCore.QRect(1010, 500, 251, 16))
        self.heightWidthGaplengthLabel_2.setObjectName("heightWidthGaplengthLabel_2")
        self.decimalSeparatorTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.decimalSeparatorTextEdit.setEnabled(True)
        self.decimalSeparatorTextEdit.setGeometry(QtCore.QRect(410, 10, 61, 21))
        self.decimalSeparatorTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decimalSeparatorTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decimalSeparatorTextEdit.setObjectName("decimalSeparatorTextEdit")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(280, 10, 141, 21))
        self.label_14.setObjectName("label_14")
        self.graphicsView.raise_()
        self.timeseriesgraphWidget.raise_()
        self.selectData.raise_()
        self.tableView.raise_()
        self.startIndex.raise_()
        self.endIndex.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.clearAndPlotData_button.raise_()
        self.button_Update.raise_()
        self.graphicsView_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.savitzkyOrder.raise_()
        self.savitzkyLength.raise_()
        self.savitzkyCheckbox.raise_()
        self.label_7.raise_()
        self.highpassCheckbox.raise_()
        self.labelSavitzkyOrder.raise_()
        self.labelSavitzkyLength.raise_()
        self.labelHighpassCutoff.raise_()
        self.highpassCutoff.raise_()
        self.label_8.raise_()
        self.detrendCheckbox.raise_()
        self.detrendBreakpointsLineEdit.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.alsLineEdit.raise_()
        self.label_12.raise_()
        self.alsCheckbox.raise_()
        self.loadDisplacementWidget.raise_()
        self.label_13.raise_()
        self.currentFilePathLabel.raise_()
        self.heightWidthGaplengthLineEdit.raise_()
        self.heightWidthGaplengthLabel.raise_()
        self.convertToStressStrainButton.raise_()
        self.convertToLoadDisplacement.raise_()
        self.youngsModulusTextEdit.raise_()
        self.heightWidthGaplengthLabel_2.raise_()
        self.decimalSeparatorTextEdit.raise_()
        self.label_14.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1192, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectData.setText(_translate("MainWindow", "Select File"))
        self.label.setText(_translate("MainWindow", "Start Index"))
        self.label_2.setText(_translate("MainWindow", "End Index"))
        self.clearAndPlotData_button.setText(_translate("MainWindow", "Reset and Plot Data"))
        self.button_Update.setText(_translate("MainWindow", "Update"))
        self.label_3.setText(_translate("MainWindow", "Filters"))
        self.label_4.setText(_translate("MainWindow", "Savitky-Golay"))
        self.label_5.setText(_translate("MainWindow", "Order"))
        self.label_6.setText(_translate("MainWindow", "Window length"))
        self.label_7.setText(_translate("MainWindow", "High-Pass"))
        self.labelSavitzkyOrder.setText(_translate("MainWindow", "ORDER"))
        self.labelSavitzkyLength.setText(_translate("MainWindow", "LENGTH"))
        self.labelHighpassCutoff.setText(_translate("MainWindow", "Cutoff"))
        self.label_8.setText(_translate("MainWindow", "Detrend"))
        self.detrendBreakpointsLineEdit.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Breakpoints"))
        self.label_10.setText(_translate("MainWindow", "All data = 0, otherwise comma separated \"0,100\""))
        self.label_11.setText(_translate("MainWindow", "Asymmetric Least Squares"))
        self.alsLineEdit.setText(_translate("MainWindow", "1000000, 0.01"))
        self.label_12.setText(_translate("MainWindow", "10^2 ≤ λ ≤ 10^9,  0.001 ≤ p ≤ 0.1"))
        self.label_13.setText(_translate("MainWindow", "Data loaded:"))
        self.heightWidthGaplengthLineEdit.setText(_translate("MainWindow", "1,1,1"))
        self.heightWidthGaplengthLabel.setText(_translate("MainWindow", "Height, Width, Gap length [mm], e.g. \"1,3,10\""))
        self.convertToStressStrainButton.setText(_translate("MainWindow", "Stress-Strain"))
        self.convertToLoadDisplacement.setText(_translate("MainWindow", "Load-Displacement"))
        self.heightWidthGaplengthLabel_2.setText(_translate("MainWindow", "Young\'s Modulus [N/mm²]"))
        self.decimalSeparatorTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Specify decimal separator:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
from pyqtgraph import PlotWidget
